
name: "Release Stable Version"

on:
  workflow_dispatch:
    inputs:
      git_tag:
        description: 'Git tag'
        required: true
        type: string
      cu:
        description: 'CUDA version'
        required: true
        type: string
        default: "121"
      python_minor:
        description: 'Python minor version'
        required: true
        type: string
        default: "11"
      python_patch:
        description: 'Python patch version'
        required: true
        type: string
        default: "9"


jobs:
  package_comcells2_windows:
    permissions:
      contents: "write"
      packages: "write"
      pull-requests: "read"
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ inputs.git_tag }}
          fetch-depth: 0
          persist-credentials: false
      - uses: actions/cache/restore@v4
        id: cache
        with:
          path: |
            cu${{ inputs.cu }}_python_deps.tar
            update_comcells2ui_and_python_dependencies.bat
          key: ${{ runner.os }}-build-cu${{ inputs.cu }}-${{ inputs.python_minor }}
      - shell: bash
        run: |
          mv cu${{ inputs.cu }}_python_deps.tar ../
          mv update_comcells2ui_and_python_dependencies.bat ../
          cd ..
          tar xf cu${{ inputs.cu }}_python_deps.tar
          pwd
          ls

      - shell: bash
        run: |
          cd ..
          cp -r Comcells2 Comcells2_copy
          curl https://www.python.org/ftp/python/3.${{ inputs.python_minor }}.${{ inputs.python_patch }}/python-3.${{ inputs.python_minor }}.${{ inputs.python_patch }}-embed-amd64.zip -o python_embeded.zip
          unzip python_embeded.zip -d python_embeded
          cd python_embeded
          echo ${{ env.MINOR_VERSION }}
          echo 'import site' >> ./python3${{ inputs.python_minor }}._pth
          curl https://bootstrap.pypa.io/get-pip.py -o get-pip.py
          ./python.exe get-pip.py
          ./python.exe -s -m pip install ../cu${{ inputs.cu }}_python_deps/*
            sed -i '1i../Comcells2' ./python3${{ inputs.python_minor }}._pth
            cd ..

          git clone --depth 1 https://github.com/comcells2anonymous/taesd
          cp taesd/*.pth ./Comcells2_copy/models/vae_approx/

          mkdir Comcells2_windows_portable
          mv python_embeded Comcells2_windows_portable
          mv Comcells2_copy Comcells2_windows_portable/Comcells2

          cd Comcells2_windows_portable

          mkdir update
          cp -r Comcells2/.ci/update_windows/* ./update/
          cp -r Comcells2/.ci/windows_base_files/* ./
          cp ../update_comcells2ui_and_python_dependencies.bat ./update/

          cd ..

          "C:\Program Files\7-Zip\7z.exe" a -t7z -m0=lzma2 -mx=8 -mfb=64 -md=32m -ms=on -mf=BCJ2 Comcells2_windows_portable.7z Comcells2_windows_portable
          mv Comcells2_windows_portable.7z Comcells2/Comcells2_windows_portable_nvidia.7z

          cd Comcells2_windows_portable
          python_embeded/python.exe -s Comcells2/main.py --quick-test-for-ci --cpu

          ls

      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: Comcells2_windows_portable_nvidia.7z
          tag: ${{ inputs.git_tag }}
          overwrite: true
          prerelease: true
          make_latest: false
